//! Build-time release metadata for the Valkey/Redis-compatible server.
//!
//! Corresponds to `release.c` and `release.h` in the Valkey C source.
//! Constants from `version.h` (which `release.h` `#include`s) are defined
//! canonically in `crate::version` and re-exported here, per the
//! PORTING.md rule that headers fold into the `.rs` that uses them — except
//! where `file-deps.tsv` assigns a header its own target file.
//!
//! In production, `REDIS_GIT_SHA1`, `REDIS_GIT_DIRTY`, and `REDIS_BUILD_ID`
//! would be injected by `build.rs` (querying `git describe`).  Phase A
//! hard-codes the values that were baked into `release.h` at snapshot time.
//!
//! # Phase A note
//! This file does not need to compile.  Name-resolution errors against
//! `crate::version` (not yet declared in `lib.rs`) are expected.

// PORT NOTE: In the C build system, release.h is regenerated by the Makefile
// on every git commit that changes SHA1 or dirty status.  In Rust the
// idiomatic replacement is a build.rs that writes constants into
// $OUT_DIR/release.rs and includes them via include!().  Phase B should
// introduce that mechanism and remove the hard-coded literals below.

use std::sync::OnceLock;

// ── Constants from release.h ─────────────────────────────────────────────────
//
// These three are defined directly in release.h (not version.h), so they
// live here rather than in crate::version.

/// Git SHA1 short hash of the build.
///
/// C: `#define REDIS_GIT_SHA1 "0321a69e"` in `release.h`.
pub const REDIS_GIT_SHA1: &[u8] = b"0321a69e";

/// Build-system dirty-flag string.  Leading whitespace is intentional —
/// it matches the C definition exactly for wire-diff parity.
///
/// C: `#define REDIS_GIT_DIRTY "       0"` in `release.h`.
pub const REDIS_GIT_DIRTY: &[u8] = b"       0";

/// Opaque build-ID tag supplied by the build environment.
///
/// C: `#define REDIS_BUILD_ID "Mac-1778952780"` in `release.h`.
const REDIS_BUILD_ID: &[u8] = b"Mac-1778952780";

// ── Re-exports from version.h (assigned to crate::version) ──────────────────
//
// release.h includes version.h, so callers that previously #include'd
// release.h transitively expected these names.  They are defined
// canonically in crate::version; re-exported here for backward
// compatibility with any code that imports from this module.
//
// TODO(port): crate::version does not yet exist (version.h → redis-core/src/version.rs
// is phase "later" and has not been translated).  These re-exports will
// produce "unresolved import" errors until that module is created — which
// is expected Phase A behaviour.
pub use crate::version::REDIS_VERSION;
pub use crate::version::REDIS_VERSION_NUM;
pub use crate::version::SERVER_NAME;
pub use crate::version::SERVER_TITLE;
pub use crate::version::VALKEY_RELEASE_STAGE;
pub use crate::version::VALKEY_VERSION;
pub use crate::version::VALKEY_VERSION_NUM;

// ── Public API ────────────────────────────────────────────────────────────────

/// Returns the Git SHA1 short hash of the current build as a byte slice.
///
/// C: `release.c:40-42, serverGitSHA1`
pub fn server_git_sha1() -> &'static [u8] {
    REDIS_GIT_SHA1
}

/// Returns the build-system dirty-flag string as a byte slice.
///
/// C: `release.c:44-46, serverGitDirty`
pub fn server_git_dirty() -> &'static [u8] {
    REDIS_GIT_DIRTY
}

/// Returns the raw build-ID string used to compute the build fingerprint.
///
/// In C this is the preprocessor concatenation:
/// `SERVER_NAME VALKEY_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1`
///
/// Rust cannot perform compile-time concatenation of separate `&[u8]`
/// constants, so the string is assembled once at first call and cached in a
/// `OnceLock`.
///
/// C: `release.c:48-50, serverBuildIdRaw`
///
/// # PORT NOTE
/// The C version returns a `const char *` pointing directly at a compile-time
/// string literal.  The Rust version returns a `&'static [u8]` pointing into a
/// heap-allocated `Vec<u8>` held by a `OnceLock`.  Behaviour is identical at
/// call sites; the allocation happens at most once.
// TODO(port): If a const-fn approach to byte-slice concatenation becomes
// stable, replace the OnceLock with a true const.
pub fn server_build_id_raw() -> &'static [u8] {
    static RAW: OnceLock<Vec<u8>> = OnceLock::new();
    RAW.get_or_init(|| {
        // Concatenation order must match the C macro definition exactly:
        //   SERVER_NAME VALKEY_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
        let mut v: Vec<u8> = Vec::new();
        v.extend_from_slice(SERVER_NAME);
        v.extend_from_slice(VALKEY_VERSION);
        v.extend_from_slice(REDIS_BUILD_ID);
        v.extend_from_slice(REDIS_GIT_DIRTY);
        v.extend_from_slice(REDIS_GIT_SHA1);
        v
    })
}

/// Computes the CRC-64 fingerprint of the raw build-ID string.
///
/// C: `release.c:52-56, serverBuildId`
///
/// ```c
/// uint64_t serverBuildId(void) {
///     char *buildid = REDIS_BUILD_ID_RAW;
///     return crc64(0, (unsigned char *)buildid, strlen(buildid));
/// }
/// ```
///
/// # TODO(architect): cross-crate CRC-64 dependency
/// The C implementation calls `crc64()` from `crc64.c`, which `file-deps.tsv`
/// maps to `redis-persist::crc64_crc64`.  `redis-core` has no declared
/// dependency on `redis-persist`.  The architect must choose one of:
///   (a) add a dep edge `redis-core → redis-persist`, or
///   (b) move `crc64` into a shared utility crate (e.g. `redis-util`) that
///       both `redis-core` and `redis-persist` can depend on.
// TODO(architect): crc64 lives in redis-persist::crc64_crc64; redis-core has no
// dep edge to redis-persist.  Resolve the crate layout before wiring the
// actual computation.  The placeholder below returns 0 to unblock callers.
pub fn server_build_id() -> u64 {
    // C: crc64(0, (unsigned char *)buildid, strlen(buildid))
    // TODO(port): replace the placeholder with
    //   redis_persist::crc64_crc64::crc64(0, server_build_id_raw())
    // once the architect resolves the dependency above.
    let _raw = server_build_id_raw();
    0
}

/// Returns a cached lowercase-hex string of the build ID as a byte slice.
///
/// Used in the INFO command output, so it must be fast after the first call.
/// The C implementation uses a static char buffer and an int flag; Rust uses
/// `OnceLock<Vec<u8>>` for the same once-init guarantee with safe concurrency.
///
/// C: `release.c:61-69, serverBuildIdString`
///
/// ```c
/// char *serverBuildIdString(void) {
///     static char buf[32];
///     static int cached = 0;
///     if (!cached) {
///         snprintf(buf, sizeof(buf), "%llx", (unsigned long long)serverBuildId());
///         cached = 1;
///     }
///     return buf;
/// }
/// ```
///
/// # PORT NOTE
/// C uses `%llx` (lowercase hex, no padding), which matches Rust's `{:x}`.
/// The `format!` call produces a `String` of ASCII hex digits; `.into_bytes()`
/// converts to `Vec<u8>` without any charset conversion of Redis data —
/// this is a Rust-internal numeric formatting step, not Redis data handling.
pub fn server_build_id_string() -> &'static [u8] {
    static CACHED: OnceLock<Vec<u8>> = OnceLock::new();
    CACHED.get_or_init(|| {
        // C: snprintf(buf, sizeof(buf), "%llx", (unsigned long long)serverBuildId())
        format!("{:x}", server_build_id()).into_bytes()
    })
}

// ──────────────────────────────────────────────────────────────────────────
// PORT STATUS
//   source:        src/release.c  (69 lines, 4 functions) + release.h + version.h
//   target_crate:  redis-core
//   confidence:    medium
//   todos:         4
//   port_notes:    3
//   unsafe_blocks: 0
//   notes:         CRC-64 dependency unresolved (placeholder returns 0); version.h
//                  re-exports will error until crate::version is created; build.rs
//                  injection of git metadata is a Phase B task.
// ──────────────────────────────────────────────────────────────────────────
