#!/usr/bin/env python3
"""Generate command registry from Valkey command JSON specs.

Reads `reference/valkey/src/commands/*.json` and produces:
  - `harness/command-registry.json` — canonical machine-readable index
  - `crates/redis-commands/src/generated.rs` — Rust definitions
    (CommandSpec table + CommandFlag/AclCategory enums)

The generated Rust is the SINGLE SOURCE OF TRUTH for command metadata.
Hand-edits are forbidden (caught by the chassis forbidden-pattern hook
when we add a `do not hand-edit` marker check; for now, just rely on
convention + commit messages).

Subcommands (e.g. `ACL CAT`, `CLUSTER NODES`) are emitted with names
like `ACL|CAT`, `CLUSTER|NODES` so the parser can route on the first
token.

Usage:
    python3 harness/gen-command-registry.py
    python3 harness/gen-command-registry.py --check    # verify in-sync, exit 1 if stale
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMANDS_DIR = ROOT / "reference" / "valkey" / "src" / "commands"
REGISTRY_JSON = ROOT / "harness" / "command-registry.json"
GENERATED_RS = ROOT / "crates" / "redis-commands" / "src" / "generated.rs"

# Header for the generated Rust file. The `do not hand-edit` line is
# load-bearing — a future chassis hook will refuse commits that change
# this file outside of a regenerated state.
GEN_HEADER = """\
// Auto-generated by harness/gen-command-registry.py from
// reference/valkey/src/commands/*.json. DO NOT HAND-EDIT.
//
// Regenerate after pulling new upstream by running:
//     python3 harness/gen-command-registry.py
//
// Total commands: {n_commands}
// Source commit: see harness/source.toml

#![allow(dead_code, non_camel_case_types, clippy::needless_borrow, clippy::redundant_static_lifetimes)]

"""


@dataclasses.dataclass(frozen=True)
class CommandSpec:
    name: str  # PING, or ACL|CAT for subcommands
    arity: int
    function: str  # C function name; informational
    group: str
    flags: tuple[str, ...]
    acl_categories: tuple[str, ...]
    key_specs: tuple[dict, ...]
    arguments: tuple[dict, ...]
    since: str
    deprecated_since: str | None


def load_command_file(path: Path) -> list[CommandSpec]:
    """A command JSON file may define one top-level command and zero or
    more subcommands (nested under `subcommands`). Returns all flattened."""
    with path.open() as f:
        doc = json.load(f)

    out = []
    for name, body in doc.items():
        out.append(_to_spec(name, body))
        for sub_name, sub_body in (body.get("subcommands") or {}).items():
            # sub_name comes in as e.g. "ACL_CAT"; reshape to "ACL|CAT"
            qualified = f"{name}|{sub_name.split('_', 1)[1]}" if "_" in sub_name else f"{name}|{sub_name}"
            out.append(_to_spec(qualified, sub_body))
    return out


def _to_spec(name: str, body: dict) -> CommandSpec:
    return CommandSpec(
        name=name,
        arity=body.get("arity", 0),
        function=body.get("function", ""),
        group=body.get("group", ""),
        flags=tuple(body.get("command_flags") or []),
        acl_categories=tuple(body.get("acl_categories") or []),
        key_specs=tuple(body.get("key_specs") or []),
        arguments=tuple(body.get("arguments") or []),
        since=body.get("since", ""),
        deprecated_since=body.get("deprecated_since"),
    )


def emit_json(specs: list[CommandSpec]) -> str:
    """Canonical JSON registry. Sorted by name for deterministic diffs."""
    data = {
        "_meta": {
            "source": "reference/valkey/src/commands/*.json",
            "count": len(specs),
            "generator": "harness/gen-command-registry.py",
        },
        "commands": {
            s.name: {
                "arity": s.arity,
                "function": s.function,
                "group": s.group,
                "flags": list(s.flags),
                "acl_categories": list(s.acl_categories),
                "key_specs": list(s.key_specs),
                "arguments": list(s.arguments),
                "since": s.since,
                "deprecated_since": s.deprecated_since,
            }
            for s in sorted(specs, key=lambda s: s.name)
        },
    }
    return json.dumps(data, indent=2, sort_keys=False) + "\n"


def _rust_ident(name: str) -> str:
    """Turn ACL|CAT or CLUSTER-FAILOVER or similar into a Rust identifier."""
    out = re.sub(r"[^A-Za-z0-9]", "_", name)
    if out and out[0].isdigit():
        out = "_" + out
    return out.upper()


def _all_flags(specs: list[CommandSpec]) -> list[str]:
    seen: set[str] = set()
    for s in specs:
        seen.update(s.flags)
    return sorted(seen)


def _all_acl_categories(specs: list[CommandSpec]) -> list[str]:
    seen: set[str] = set()
    for s in specs:
        seen.update(s.acl_categories)
    return sorted(seen)


def emit_rust(specs: list[CommandSpec]) -> str:
    """Rust source for crates/redis-commands/src/generated.rs.

    Keeps the output deliberately minimal — just the metadata that's
    useful for command dispatch, arity check, and reply schema lookup.
    Reply-schema details and argument trees are left as `&'static str`
    (raw JSON) for downstream code to parse on demand; including them
    inline would balloon the generated file with no immediate benefit.
    """
    lines = [GEN_HEADER.format(n_commands=len(specs))]

    # Enums
    lines.append("/// All command flags seen across commands. Source order matches Valkey.")
    lines.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    lines.append("pub enum CommandFlag {")
    for f in _all_flags(specs):
        lines.append(f"    {_rust_ident(f)},")
    lines.append("}")
    lines.append("")

    lines.append("/// ACL categories.")
    lines.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    lines.append("pub enum AclCategory {")
    for c in _all_acl_categories(specs):
        lines.append(f"    {_rust_ident(c)},")
    lines.append("}")
    lines.append("")

    # Spec struct
    lines.append("/// Static metadata for a Valkey command.")
    lines.append("/// `key_specs_json` and `arguments_json` hold the raw JSON arrays")
    lines.append("/// (parse on demand to avoid bloating the generated file).")
    lines.append("#[derive(Debug, Clone, Copy)]")
    lines.append("pub struct GeneratedCommandSpec {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub arity: i32,")
    lines.append("    pub function: &'static str,")
    lines.append("    pub group: &'static str,")
    lines.append("    pub flags: &'static [CommandFlag],")
    lines.append("    pub acl_categories: &'static [AclCategory],")
    lines.append("    pub key_specs_json: &'static str,")
    lines.append("    pub arguments_json: &'static str,")
    lines.append("    pub since: &'static str,")
    lines.append("    pub deprecated_since: Option<&'static str>,")
    lines.append("}")
    lines.append("")

    # Static table
    lines.append(f"pub static COMMANDS: &[GeneratedCommandSpec] = &[")
    for s in sorted(specs, key=lambda s: s.name):
        flag_list = ", ".join(f"CommandFlag::{_rust_ident(f)}" for f in s.flags) or ""
        acl_list = ", ".join(f"AclCategory::{_rust_ident(c)}" for c in s.acl_categories) or ""
        key_specs_json = _escape_rust(json.dumps(list(s.key_specs)))
        args_json = _escape_rust(json.dumps(list(s.arguments)))
        deprecated = f'Some("{s.deprecated_since}")' if s.deprecated_since else "None"
        lines.append("    GeneratedCommandSpec {")
        lines.append(f'        name: "{s.name}",')
        lines.append(f"        arity: {s.arity},")
        lines.append(f'        function: "{s.function}",')
        lines.append(f'        group: "{s.group}",')
        lines.append(f"        flags: &[{flag_list}],")
        lines.append(f"        acl_categories: &[{acl_list}],")
        lines.append(f'        key_specs_json: "{key_specs_json}",')
        lines.append(f'        arguments_json: "{args_json}",')
        lines.append(f'        since: "{s.since}",')
        lines.append(f"        deprecated_since: {deprecated},")
        lines.append("    },")
    lines.append("];")
    lines.append("")

    # Trailer (required by the trailer-required hook)
    lines.append("// ──────────────────────────────────────────────────────────────────────")
    lines.append("// PORT STATUS")
    lines.append("//   source:        reference/valkey/src/commands/*.json")
    lines.append("//   target_crate:  redis-commands")
    lines.append("//   confidence:    high")
    lines.append("//   todos:         0")
    lines.append("//   port_notes:    0")
    lines.append("//   unsafe_blocks: 0")
    lines.append(f"//   notes:         generated by harness/gen-command-registry.py from {len(specs)} commands")
    lines.append("// ──────────────────────────────────────────────────────────────────────")
    lines.append("")
    return "\n".join(lines)


def _escape_rust(s: str) -> str:
    """Escape a string for a Rust string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Verify in-sync; exit 1 if regeneration would change anything.")
    args = ap.parse_args()

    if not COMMANDS_DIR.is_dir():
        print(f"FATAL: {COMMANDS_DIR} not found. Run harness/bootstrap-upstream.sh first.",
              file=sys.stderr)
        return 2

    specs: list[CommandSpec] = []
    for p in sorted(COMMANDS_DIR.glob("*.json")):
        specs.extend(load_command_file(p))

    if not specs:
        print(f"FATAL: no command specs loaded from {COMMANDS_DIR}", file=sys.stderr)
        return 2

    json_out = emit_json(specs)
    rust_out = emit_rust(specs)

    if args.check:
        old_json = REGISTRY_JSON.read_text() if REGISTRY_JSON.exists() else ""
        old_rust = GENERATED_RS.read_text() if GENERATED_RS.exists() else ""
        stale = []
        if old_json != json_out:
            stale.append(str(REGISTRY_JSON.relative_to(ROOT)))
        if old_rust != rust_out:
            stale.append(str(GENERATED_RS.relative_to(ROOT)))
        if stale:
            print("STALE: " + ", ".join(stale), file=sys.stderr)
            print("Run `python3 harness/gen-command-registry.py` to regenerate.", file=sys.stderr)
            return 1
        print(f"OK: registry in sync ({len(specs)} commands)")
        return 0

    REGISTRY_JSON.write_text(json_out)
    GENERATED_RS.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_RS.write_text(rust_out)
    print(f"wrote {REGISTRY_JSON.relative_to(ROOT)} ({len(specs)} commands, "
          f"{len(_all_flags(specs))} flags, {len(_all_acl_categories(specs))} acl categories)")
    print(f"wrote {GENERATED_RS.relative_to(ROOT)} ({rust_out.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
