//! RESP reply parser — callback-driven incremental parser for RESP2 and RESP3 replies.
//! # Design
//! The C design stored both buffer position (`curr_location`) and a struct
//! function pointers (`ReplyParserCallbacks`) inside a single `ReplyParser` struct.
//! Collection-type callbacks (array, set, map, attribute) received `*parser` so
//! they could call `parseReply(parser, nested_ctx)` recursively — a self-referential
//! pointer pattern that produces a borrow conflict in Rust.
//! The two concerns are therefore split:
//! - [`ParserCursor`] holds the mutable buffer position (the `curr_location` analogue).
//! - [`ParserCallbacks`] trait replaces the C function-pointer struct.
//! - Collection callbacks (`on_array`, `on_set`, `on_map`, `on_attribute`) receive
//! `&mut ParserCursor` and call `cursor.parse_next(self)` to consume nested frames.
//! The `void *p_ctx` parameter from every C callback is replaced by `&mut self` on
//! the trait implementor — the implementor IS the context.
//! # Warning (from C source)
//! This parser is designed only for replies generated by Valkey itself (e.g.
//! `RM_Call` or Lua's `redis.call`). It does **not** perform the validations
//! required for untrusted user input.

use redis_types::RedisError;

/// Maximum byte length of a RESP3 double value before the parser treats it
/// as zero rather than attempting floating-point conversion.
/// `#define MAX_LONG_DOUBLE_CHARS 5 * 1024`
const MAX_LONG_DOUBLE_CHARS: usize = 5 * 1024;

/// Callback interface invoked by [`ParserCursor::parse_next`] for each RESP frame type.
/// Implement this trait to receive decoded frames. For scalar types the callback
/// receives the decoded value plus the raw protocol bytes (`proto`). For aggregate
/// types (array, set, map, attribute) the callback receives a `&mut ParserCursor`
/// and must call `cursor.parse_next(self)` the appropriate number of times
/// consume the nested frames.
/// `ReplyParserCallbacks`
/// PORT NOTE: The `void *p_ctx` parameter present on every C callback is replaced by
/// `&mut self` on the implementor. Nested contexts for collection types must be
/// managed by the implementor itself (e.g. via a stack field), rather than passing a
/// different `p_ctx` per recursive `parseReply` call as the C design allows.
pub trait ParserCallbacks {
 /// Null bulk string (`$-1\r\n`). `proto` is the entire frame bytes.
    fn on_null_bulk_string(&mut self, proto: &[u8]);

 /// Null array (`*-1\r\n`). `proto` is the entire frame bytes.
    fn on_null_array(&mut self, proto: &[u8]);

 /// Non-null bulk string (`$<len>\r\n<data>\r\n`).
 /// `data` is the payload; `proto` is the full frame including prefix and CRLFs.
    fn on_bulk_string(&mut self, data: &[u8], proto: &[u8]);

 /// Error reply (`-<msg>\r\n`).
 /// `data` is the message bytes without the leading `-`; `proto` is the full frame.
    fn on_error(&mut self, data: &[u8], proto: &[u8]);

 /// Simple string reply (`+<msg>\r\n`).
 /// `data` is the message bytes without the leading `+`; `proto` is the full frame.
    fn on_simple_str(&mut self, data: &[u8], proto: &[u8]);

 /// Integer reply (`:<n>\r\n`). `proto` is the full frame.
    fn on_long(&mut self, val: i64, proto: &[u8]);

 /// Array aggregate (`*<n>\r\n`).
 /// Must call `cursor.parse_next(self)` exactly `len` times to consume elements.
 /// Note: `proto` covers only the header line; the aggregate frame length is not
 /// known at invocation time (matching C behaviour).
    fn on_array(&mut self, cursor: &mut ParserCursor<'_>, len: i64, proto: &[u8]);

 /// RESP3 set aggregate (`~<n>\r\n`).
 /// Must call `cursor.parse_next(self)` exactly `len` times.
    fn on_set(&mut self, cursor: &mut ParserCursor<'_>, len: i64, proto: &[u8]);

 /// RESP3 map aggregate (`%<n>\r\n`).
 /// Must call `cursor.parse_next(self)` exactly `2 * len` times (key then value per pair).
    fn on_map(&mut self, cursor: &mut ParserCursor<'_>, len: i64, proto: &[u8]);

 /// RESP3 boolean (`#t\r\n` → `true`; `#f\r\n` → `false`).
    fn on_bool(&mut self, val: bool, proto: &[u8]);

 /// RESP3 double (`,<repr>\r\n`). `proto` is the full frame.
    fn on_double(&mut self, val: f64, proto: &[u8]);

 /// RESP3 big number (`(<digits>\r\n`).
 /// `data` is the digit bytes without the leading `(`; `proto` is the full frame.
    fn on_big_number(&mut self, data: &[u8], proto: &[u8]);

 /// RESP3 verbatim string (`=<totlen>\r\n<3chars>:<data>\r\n`).
 /// `format` is the 3-byte type tag (e.g. `b"txt"` or `b"mkd"`).
 /// `data` is the payload after the `<tag>:` separator; `proto` is the full frame.
    fn on_verbatim_string(&mut self, format: &[u8], data: &[u8], proto: &[u8]);

 /// RESP3 attribute aggregate (`|<n>\r\n`).
 /// Must call `cursor.parse_next(self)` exactly `2 * len` times (key then value per pair).
 /// `proto` covers only the header line.
    fn on_attribute(&mut self, cursor: &mut ParserCursor<'_>, len: i64, proto: &[u8]);

 /// RESP3 null (`_\r\n`). `proto` is the full frame.
    fn on_null(&mut self, proto: &[u8]);

 /// Called when the parser encounters an unknown type byte.
 /// The cursor is NOT advanced. Implementations should treat this as a fatal error.
    fn on_parse_error(&mut self);
}

/// Incremental RESP reply parser.
/// Wraps a borrowed byte slice and a current position. Create with [`ParserCursor::new`],
/// then call [`ParserCursor::parse_next`] once per expected reply frame, passing a
/// [`ParserCallbacks`] implementor.
/// `struct ReplyParser` (buffer-position half only;
/// the callback half is now the [`ParserCallbacks`] trait).
pub struct ParserCursor<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> ParserCursor<'a> {
 /// Create a cursor at the start of `buf`.
    pub fn new(buf: &'a [u8]) -> Self {
        Self { buf, pos: 0 }
    }

 /// Number of bytes not yet consumed.
    pub fn remaining(&self) -> usize {
        self.buf.len().saturating_sub(self.pos)
    }

 /// Byte slice of the unconsumed tail.
    pub fn remaining_bytes(&self) -> &'a [u8] {
        &self.buf[self.pos..]
    }

 /// Parse one RESP frame and dispatch to the appropriate callback on `cb`.
 /// Returns `Ok(` after the callback returns. Returns `Err` if the buffer
 /// is exhausted, the frame is malformed, or an unknown type byte is encountered
 /// (after calling `cb.on_parse_error`).
 /// `parseReply`
    pub fn parse_next(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let byte = self
            .buf
            .get(self.pos)
            .copied()
            .ok_or_else(|| RedisError::runtime(b"resp parser: buffer exhausted"))?;

        match byte {
            b'$' => self.parse_bulk(cb),
            b'+' => self.parse_simple_string(cb),
            b'-' => self.parse_error(cb),
            b':' => self.parse_long(cb),
            b'*' => self.parse_array(cb),
            b'~' => self.parse_set(cb),
            b'%' => self.parse_map(cb),
            b'#' => self.parse_bool(cb),
            b',' => self.parse_double(cb),
            b'_' => self.parse_null(cb),
            b'(' => self.parse_big_number(cb),
            b'=' => self.parse_verbatim_string(cb),
            b'|' => self.parse_attributes(cb),
            _ => {
                cb.on_parse_error();
                Err(RedisError::runtime(b"resp parser: unknown RESP type byte"))
            }
        }
    }

 // ── private frame parsers ─────────────────────────────────────────────

 /// `parseBulk`
    fn parse_bulk(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let bulklen = parse_i64(&self.buf[self.pos + 1..cr])?;
        self.pos = cr + 2; // advance past length-line CRLF

        if bulklen == -1 {
            let proto = &self.buf[proto_start..self.pos];
            cb.on_null_bulk_string(proto);
        } else if bulklen < -1 {
            return Err(RedisError::runtime(b"resp parser: invalid bulk length"));
        } else {
            let data_start = self.pos;
            let data_len = bulklen as usize;
            let data_end = data_start
                .checked_add(data_len)
                .ok_or_else(|| RedisError::runtime(b"resp parser: bulk length overflow"))?;
            self.pos = data_end + 2; // advance past data + trailing CRLF
            let data = &self.buf[data_start..data_end];
            let proto = &self.buf[proto_start..self.pos];
            cb.on_bulk_string(data, proto);
        }
        Ok(())
    }

 /// `parseSimpleString`
    fn parse_simple_string(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let data = &self.buf[self.pos + 1..cr];
        self.pos = cr + 2; // advance past CRLF
        let proto = &self.buf[proto_start..self.pos];
        cb.on_simple_str(data, proto);
        Ok(())
    }

 /// `parseError`
    fn parse_error(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let data = &self.buf[self.pos + 1..cr];
        self.pos = cr + 2; // advance past CRLF
        let proto = &self.buf[proto_start..self.pos];
        cb.on_error(data, proto);
        Ok(())
    }

 /// `parseLong`
    fn parse_long(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let val = parse_i64(&self.buf[self.pos + 1..cr])?;
        self.pos = cr + 2; // advance past CRLF
        let proto = &self.buf[proto_start..self.pos];
        cb.on_long(val, proto);
        Ok(())
    }

 /// `parseAttributes`
 /// PORT NOTE: `proto` covers only the attribute header line (type byte
 /// length + CRLF), not the nested key/value frames. This matches C behaviour
 /// where `proto` is captured before advancing past the nested frames.
    fn parse_attributes(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let len = parse_i64(&self.buf[self.pos + 1..cr])?;
        self.pos = cr + 2; // advance past header CRLF; nested frames follow

        // TODO(port): borrow-lifetime — `proto` is a &'a [u8] slice reborrowed from
 // self.buf (lifetime 'a), so it should not conflict with &mut self passed
 // on_attribute. Verify with the Phase B compiler pass; if the borrow checker
 // rejects this, capture proto as Vec<u8> before the mutable re-borrow.
        let proto = &self.buf[proto_start..self.pos];
        cb.on_attribute(self, len, proto);
        Ok(())
    }

 /// `parseVerbatimString`
 /// Wire layout: `=<totlen>\r\n<3-byte-tag>:<data>\r\n`
 /// where `totlen = 3 (tag) + 1 (colon) + data.len`.
    fn parse_verbatim_string(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let bulklen = parse_i64(&self.buf[self.pos + 1..cr])? as usize;
        self.pos = cr + 2; // advance to start of payload (past length CRLF)

        if bulklen < 4 {
            return Err(RedisError::runtime(
                b"resp parser: verbatim string payload too short",
            ));
        }
        let format = &self.buf[self.pos..self.pos + 3]; // 3-byte format tag (e.g. b"txt")
 // Byte at self.pos + 3 is ':' separator — not passed to callback.
        let data_end = self.pos + bulklen;
        let data = &self.buf[self.pos + 4..data_end]; // payload after "tag:"
        self.pos = data_end + 2; // advance past payload + trailing CRLF
        let proto = &self.buf[proto_start..self.pos];
        cb.on_verbatim_string(format, data, proto);
        Ok(())
    }

 /// `parseBigNumber`
    fn parse_big_number(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let data = &self.buf[self.pos + 1..cr]; // digit bytes, no leading '('
        self.pos = cr + 2; // advance past CRLF
        let proto = &self.buf[proto_start..self.pos];
        cb.on_big_number(data, proto);
        Ok(())
    }

 /// `parseNull`
    fn parse_null(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        self.pos = cr + 2; // advance past CRLF
        let proto = &self.buf[proto_start..self.pos];
        cb.on_null(proto);
        Ok(())
    }

 /// `parseDouble`
 /// Guards conversion with `MAX_LONG_DOUBLE_CHARS`; returns `0.0` for
 /// pathologically long inputs (matching C behaviour where `d` stays 0).
    fn parse_double(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let repr = &self.buf[self.pos + 1..cr]; // bytes after ','
        self.pos = cr + 2; // advance past CRLF
        let proto = &self.buf[proto_start..self.pos];

        let d = parse_resp3_double(repr);
        cb.on_double(d, proto);
        Ok(())
    }

 /// `parseBool`
 /// `#t\r\n` → `true`; `#f\r\n` (or any non-`t` byte) → `false`.
    fn parse_bool(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let type_byte = self
            .buf
            .get(self.pos + 1)
            .copied()
            .ok_or_else(|| RedisError::runtime(b"resp parser: truncated boolean frame"))?;
        let cr = self.find_cr(self.pos + 1)?;
        self.pos = cr + 2; // advance past CRLF
        let proto = &self.buf[proto_start..self.pos];
        cb.on_bool(type_byte == b't', proto);
        Ok(())
    }

 /// `parseArray`
 /// A length of `-1` triggers `on_null_array` instead of `on_array`.
    fn parse_array(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let len = parse_i64(&self.buf[self.pos + 1..cr])?;
        self.pos = cr + 2; // advance past header CRLF; elements follow

        // TODO(port): borrow-lifetime — same as parse_attributes; see that note.
        let proto = &self.buf[proto_start..self.pos];
        if len == -1 {
            cb.on_null_array(proto);
        } else {
            cb.on_array(self, len, proto);
        }
        Ok(())
    }

 /// `parseSet`
    fn parse_set(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let len = parse_i64(&self.buf[self.pos + 1..cr])?;
        self.pos = cr + 2; // advance past header CRLF

        // TODO(port): borrow-lifetime — same as parse_attributes; see that note.
        let proto = &self.buf[proto_start..self.pos];
        cb.on_set(self, len, proto);
        Ok(())
    }

 /// `parseMap`
    fn parse_map(&mut self, cb: &mut dyn ParserCallbacks) -> Result<(), RedisError> {
        let proto_start = self.pos;
        let cr = self.find_cr(self.pos + 1)?;
        let len = parse_i64(&self.buf[self.pos + 1..cr])?;
        self.pos = cr + 2; // advance past header CRLF

        // TODO(port): borrow-lifetime — same as parse_attributes; see that note.
        let proto = &self.buf[proto_start..self.pos];
        cb.on_map(self, len, proto);
        Ok(())
    }

 // ── helpers ───────────────────────────────────────────────────────────

 /// Return the index of the first `\r` byte at or after `from`.
    fn find_cr(&self, from: usize) -> Result<usize, RedisError> {
        self.buf[from..]
            .iter()
            .position(|&b| b == b'\r')
            .map(|offset| from + offset)
            .ok_or_else(|| RedisError::runtime(b"resp parser: truncated frame (missing CRLF)"))
    }
}

/// Parse an ASCII decimal integer (with optional leading `-`) from `bytes`.
/// Covers all RESP integer fields: bulk lengths, array lengths, integer values.
/// Does not accept leading whitespace, trailing characters, or non-digit bytes.
fn parse_i64(bytes: &[u8]) -> Result<i64, RedisError> {
    if bytes.is_empty() {
        return Err(RedisError::not_integer());
    }
    let (negative, digits) = if bytes[0] == b'-' {
        (true, &bytes[1..])
    } else {
        (false, bytes)
    };
    if digits.is_empty() {
        return Err(RedisError::not_integer());
    }
    let mut acc: i64 = 0;
    for &b in digits {
        let d = match b {
            b'0'..=b'9' => (b - b'0') as i64,
            _ => return Err(RedisError::not_integer()),
        };
        acc = acc
            .checked_mul(10)
            .and_then(|v| v.checked_add(d))
            .ok_or_else(RedisError::not_integer)?;
    }
    Ok(if negative { -acc } else { acc })
}

/// Parse a RESP3 double representation, retaining the reference parser's
/// length guard.
fn parse_resp3_double(bytes: &[u8]) -> f64 {
    if bytes.len() <= MAX_LONG_DOUBLE_CHARS {
        parse_f64_bytes(bytes)
    } else {
        0.0
    }
}

/// Parse an ASCII floating-point number from `bytes`.
/// Handles the RESP3 special representations `inf`, `-inf`, and `nan` directly.
/// Malformed input maps to `0.0`, matching `valkey_strtod_n`'s initialized
/// output value. RESP3 double representations are ASCII by protocol.
fn parse_f64_bytes(bytes: &[u8]) -> f64 {
    match bytes {
        b"inf" => f64::INFINITY,
        b"-inf" => f64::NEG_INFINITY,
        b"nan" => f64::NAN,
        _ => std::str::from_utf8(bytes)
            .ok()
            .and_then(|value| value.parse().ok())
            .unwrap_or(0.0),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_finite_resp3_doubles() {
        assert_eq!(parse_resp3_double(b"12.5"), 12.5);
        assert_eq!(parse_resp3_double(b"-0.125"), -0.125);
        assert_eq!(parse_resp3_double(b"1.25e2"), 125.0);
        assert_eq!(parse_resp3_double(b"-4E-2"), -0.04);
    }

    #[test]
    fn preserves_signed_zero() {
        assert_eq!(parse_resp3_double(b"0").to_bits(), 0.0_f64.to_bits());
        assert_eq!(parse_resp3_double(b"-0").to_bits(), (-0.0_f64).to_bits());
    }

    #[test]
    fn parses_resp3_special_values() {
        assert_eq!(parse_resp3_double(b"inf"), f64::INFINITY);
        assert_eq!(parse_resp3_double(b"-inf"), f64::NEG_INFINITY);
        assert!(parse_resp3_double(b"nan").is_nan());
    }

    #[test]
    fn malformed_double_representations_are_zero() {
        let malformed: &[&[u8]] = &[b"", b".", b"+", b"1.2.3", b"nope"];
        for repr in malformed {
            assert_eq!(parse_resp3_double(repr), 0.0, "repr: {repr:?}");
        }
    }

    #[test]
    fn preserves_overflow_and_length_behavior() {
        assert_eq!(parse_resp3_double(b"1e9999"), f64::INFINITY);

        let at_limit = vec![b'0'; MAX_LONG_DOUBLE_CHARS];
        assert_eq!(parse_resp3_double(&at_limit), 0.0);

        let over_limit = vec![b'1'; MAX_LONG_DOUBLE_CHARS + 1];
        assert_eq!(parse_resp3_double(&over_limit), 0.0);
    }
}

// ──────────────────────────────────────────────────────────────────────────
// PORT STATUS
//   source:        Valkey
//                  src/resp_parser.h (100 lines — merged.
//   target_crate:  redis-protocol
//   confidence:    medium
//   todos:         6
//   port_notes:    2
//   unsafe_blocks: 0
//   notes:         Callback trait design resolves the C self-referential parser
//                  pointer. Four borrow-lifetime TODOs (aggregate callbacks)
//                  should resolve in Phase B with explicit 'a annotations or
//                  Vec<u8> proto copies. parse_f64_bytes is a stub for the
//                  general case — needs an approved byte-float crate in Phase B.
// ──────────────────────────────────────────────────────────────────────────
